<?php

namespace Netrunnerdb\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeckRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckRepository extends EntityRepository
{
}
