<?php

namespace Netrunnerdb\BuilderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ReviewcommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReviewcommentRepository extends EntityRepository
{
}
