AppBundle\Entity\Mwl:
    type: entity
    table: mwl
    repositoryClass: AppBundle\Repository\MWLRepository
    oneToMany:
        legalities:
            targetEntity: Legality
            mappedBy: mwl
            cascade: ["persist","remove"]
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        code:
            type: string
            length: 255
        name:
            type: string
            length: 255
        dateCreation:
            type: datetime
            column: date_creation
            gedmo:
                timestampable:
                    on:  create
        dateUpdate:
            type: datetime
            column: date_update
            gedmo:
                timestampable:
                    on:  update
        dateStart:
            type: date
            nullable: true
            column: date_start
        active:
            type: boolean
        cards:
            type: json_array
    lifecycleCallbacks: {  }
