<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DeckslotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DeckslotRepository extends EntityRepository
{
}
